version: '3.1'

services:

  life360_to_mqtt:
    image: tomgidden/life360_to_mqtt
    build: life360_to_mqtt
    volumes:
      - "./life360_to_mqtt/config.py:/app/config.py:ro"

  ical_to_mqtt:
    image: tomgidden/ical_to_mqtt
    build: ical_to_mqtt
    volumes:
      - "./ical_to_mqtt/config.py:/app/config.py:ro"

  web:
    image: nginx
    volumes:
      - "./webframe:/usr/share/nginx/html:ro"
    ports:
      - "26905:80"
