version: '3.1'

services:

  life360_to_mqtt:
    image: tomgidden/life360_to_mqtt
    build: life360_to_mqtt
    volumes:
      - "./life360_to_mqtt/config.py:/app/config.py:ro"

  ical_to_mqtt:
    image: tomgidden/ical_to_mqtt
    build: ical_to_mqtt
    volumes:
      - "./ical_to_mqtt/config.py:/app/config.py:ro"

  weather_to_mqtt:
    image: tomgidden/weather_to_mqtt
    build: weather_to_mqtt
    volumes:
      - "./weather_to_mqtt/config.py:/app/config.py:ro"

  web:
    image: nginx
    volumes:
      - "./webframe:/usr/share/nginx/html:ro"
      - "./ssl:/etc/ssl:ro"
      - "./ssl/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro"
    ports:
      - "26905:80"
      - "26906:443"
